### ISSUE TITLE
Empty `group` following `yield` causes `ClassCastException`

### ISSUE THREAD

**Issue by julianhyde** [hydromatic/morel#125]
If a `from` expression has a `yield` clause followed by an empty `group`, Morel throws `ClassCastException`.

Here is an example:
```
- from e in [1,2,3] yield e group;
java.lang.ClassCastException: net.hydromatic.morel.ast.Core$Id cannot be cast to net.hydromatic.morel.ast.Core$Tuple
	at net.hydromatic.morel.compile.Compiler.createRowSinkFactory(Compiler.java:340)
	at net.hydromatic.morel.compile.Compiler.createRowSinkFactory(Compiler.java:317)
	at net.hydromatic.morel.compile.Compiler.compileFrom(Compiler.java:293)
	at net.hydromatic.morel.compile.Compiler.compile(Compiler.java:240)
	at net.hydromatic.morel.compile.Compiler.compileArg(Compiler.java:164)
	at net.hydromatic.morel.compile.Compiler.lambda$compileValDecl$20(Compiler.java:619)
	at net.hydromatic.morel.ast.Core$NonRecValDecl.forEachBinding(Core.java:707)
	at net.hydromatic.morel.compile.Compiler.compileValDecl(Compiler.java:614)
	at net.hydromatic.morel.compile.Compiler.compileDecl(Compiler.java:501)
	at net.hydromatic.morel.compile.Compiler.compileStatement(Compiler.java:88)
	at net.hydromatic.morel.compile.Compiles.prepareDecl(Compiles.java:116)
	at net.hydromatic.morel.compile.Compiles.prepareStatement(Compiles.java:69)
	at net.hydromatic.morel.Shell$SubShell.extracted(Shell.java:480)
	at net.hydromatic.morel.Shell.run(Shell.java:264)
	at net.hydromatic.morel.Shell.main(Shell.java:88)
```

A similar query without `yield` is OK:
```
- from e in [1,2,3] group;
val it = [()] : unit list
```

Another query with the problem:
```
- from e in scott.emp where e.job = "CLERK" yield e.deptno group ;
java.lang.ClassCastException: net.hydromatic.morel.ast.Core$Apply cannot be cast to net.hydromatic.morel.ast.Core$Tuple
	at net.hydromatic.morel.compile.Compiler.createRowSinkFactory(Compiler.java:340)
```

**Comment by julianhyde** [comment]
This is related to #32. If a step yields a single anonymous field (not a record) how is the subsequent step to refer to it?

**Comment by julianhyde** [comment]
Fixed by the `group`/`compute` redesign (#288). A bare empty group is now written `group {}` and evaluates cleanly:
```sml
- from e in [1,2,3] yield e group {};
val it = [()] : unit list
```
Closing as fixed.

A single anonymous field can be referred to using `current` (see #265). #387 would allow you to assign the output of `yield`, `yieldAll` and `group` to a variable.
