### ISSUE TITLE
AssertionError in TypeResolver.deducePatType when distinct variables have the same name

### ISSUE THREAD

**Issue by julianhyde** [hydromatic/morel#197]
The function
```
fun foo (f, n) =
  let
    fun factorial 0 = 1
      | factorial n = f (n * factorial (n - 1))
  in
    factorial n
  end;
```
throws the following exception:
```
Exception in thread "main" java.lang.AssertionError
	at net.hydromatic.morel.compile.TypeResolver.deducePatType(TypeResolver.java:1117)
	at net.hydromatic.morel.compile.TypeResolver.deduceMatchListType(TypeResolver.java:675)
	at net.hydromatic.morel.compile.TypeResolver.deduceType(TypeResolver.java:303)
```

The similar function
```
fun foo (f, n) =
  let
    fun factorial 0 = 1
      | factorial k = f (k * factorial (k - 1))
  in
    factorial n
  end;
```
has no error; the only difference is that the shadowing variable `n` is renamed to `k`. Perhaps the problem is caused by duplicate variable names.

**Comment by julianhyde** [comment]
Fixed on 2023-07-29 (commit ac929a1, "Fix a problem where a parameter that shadows another parameter was assumed to be a zero-argument type constructor", which added tests in `closure.smli`). Closing as fixed.
